from pydantic import BaseModel, Field
from typing import List, Optional, Any, Dict
from app.schemas.common_schema import Customer, Metadata, ApprovalDetails, Authenticator, Risk

class PaymentAccount(BaseModel):
    payment_method: str = Field(..., description="Payment method (e.g. CreditCard, DebitCard, NetBanking)")
    cardholder_name: Optional[str] = None
    enc_card_number: Optional[str] = None
    enc_card_expiry: Optional[str] = None

class PayBillRequest(BaseModel):
    billerid: Optional[str] = Field(None, description="Unique Biller ID")
    billeraccountid: Optional[str] = Field(None, description="Registered biller account ID")
    validationid: Optional[str] = Field(None, description="Validation ID from Fetch Bill response")
    currency: str = Field("356", description="ISO currency code")
    payment_amount: Optional[str] = Field(None, description="Amount of bill payment")
    cou_conv_fee: str = Field("0.00", description="COU convenience fee")
    bou_conv_fee: str = Field("0.00", description="BOU convenience fee")
    debit_amount: Optional[str] = Field(None, description="Total amount debited from account")
    payment_type: Optional[str] = Field(None, description="Type of payment (instapay, billpay, adhoc)")
    payment_remarks: Optional[str] = None
    source_ref_no: Optional[str] = Field(None, description="Unique reference number generated by client for request")
    customer: Optional[Customer] = None
    metadata: Optional[Metadata] = None
    approval_details: Optional[ApprovalDetails] = None
    payment_account: Optional[PaymentAccount] = None
    payment_method: Optional[str] = Field(None, description="Payment method for minimal payload entry")
    risk: Optional[List[Risk]] = Field(None, description="Risk assessment tags")
    auth_code: Optional[str] = None

    model_config = {
        "json_schema_extra": {
            "example": {
                "validationid": "VAL-38134",
                "payment_method": "CARD"
            }
        }
    }

class PayBillResponse(BaseModel):
    objectid: str = "payment"
    sourceid: str
    customerid: str
    billerid: str
    biller_name: str
    biller_category: str
    billeraccountid: Optional[str] = None
    authenticators: List[Authenticator] = []
    validationid: Optional[str] = None
    payment_amount: str
    currency: str = "356"
    debit_amount: str
    payment_type: str
    source_ref_no: str
    payment_reference: str = Field(..., description="Gateway generated unique reference number")
    status: str = Field(..., description="Status of transaction: SETTLED, FAILED, PENDING")
    error_code: str = ""
    message: str = "Successful"
    payment_date: str
