# Supported channels
ALLOWED_CHANNELS = ["mbanking", "upi", "fi", "feature-phone"]

# HTTP Headers
CONTENT_TYPE_JSON = "application/json"
ACCEPT_JSON = "application/json"

# Transaction State Machine States
class TransactionState:
    INITIALIZED = "INITIALIZED"
    PENDING_SUBMISSION = "PENDING_SUBMISSION"
    NETWORK_IN_FLIGHT = "NETWORK_IN_FLIGHT"
    AMBIGUOUS_TIMEOUT = "AMBIGUOUS_TIMEOUT"
    PENDING_RETRY = "PENDING_RETRY"
    SETTLED = "SETTLED"
    FAILED = "FAILED"
    FAILED_DLQ = "FAILED_DLQ"

# Error Codes
class BBPS_ErrorCodes:
    INVALID_CHANNEL = "ERR_INVALID_CHANNEL"
    HMAC_VERIFICATION_FAILED = "ERR_HMAC_VERIFICATION_FAILED"
    TRANSACTION_FAILED = "ERR_TRANSACTION_FAILED"
    DATABASE_ERROR = "ERR_DATABASE_ERROR"
    VALIDATION_ERROR = "ERR_VALIDATION_ERROR"
    IDEMPOTENCY_VIOLATION = "ERR_IDEMPOTENCY_VIOLATION"
    REPLAY_ATTEMPT = "ERR_REPLAY_ATTEMPT"
