"""add_retry_metadata_to_transaction_logs

Revision ID: 168caa80bbfd
Revises: 804f63dbc69c
Create Date: 2026-05-25 21:15:10.301945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '168caa80bbfd'
down_revision: Union[str, Sequence[str], None] = '804f63dbc69c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('transaction_logs', sa.Column('retry_attempts', sa.Integer(), server_default='0', nullable=False))
    op.add_column('transaction_logs', sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('transaction_logs', sa.Column('worker_last_execution', sa.DateTime(timezone=True), nullable=True))
    op.add_column('transaction_logs', sa.Column('reconciliation_version', sa.Integer(), server_default='1', nullable=False))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction_logs', 'reconciliation_version')
    op.drop_column('transaction_logs', 'worker_last_execution')
    op.drop_column('transaction_logs', 'next_retry_at')
    op.drop_column('transaction_logs', 'retry_attempts')
    # ### end Alembic commands ###
