"""Initial schema

Revision ID: 5dd71be783a8
Revises: 
Create Date: 2026-05-25 20:50:22.410033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5dd71be783a8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('biller_id', sa.String(length=50), nullable=False),
    sa.Column('biller_name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billers_biller_id'), 'billers', ['biller_id'], unique=True)
    op.create_table('nonce_registry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nonce', sa.String(length=255), nullable=False),
    sa.Column('source_id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nonce_registry_nonce'), 'nonce_registry', ['nonce'], unique=True)
    op.create_table('payment_idempotency',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('payment_reference', sa.String(length=100), nullable=False),
    sa.Column('transaction_status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_reference')
    )
    op.create_index(op.f('ix_payment_idempotency_idempotency_key'), 'payment_idempotency', ['idempotency_key'], unique=True)
    op.create_table('reconciliation_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trace_id', sa.String(length=50), nullable=False),
    sa.Column('polling_attempts', sa.Integer(), nullable=False),
    sa.Column('resolved_state', sa.String(length=30), nullable=True),
    sa.Column('reconciliation_status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_logs_trace_id'), 'reconciliation_logs', ['trace_id'], unique=False)
    op.create_table('transaction_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trace_id', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.String(length=50), nullable=True),
    sa.Column('biller_id', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('transaction_state', sa.String(length=30), nullable=False),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_logs_biller_id'), 'transaction_logs', ['biller_id'], unique=False)
    op.create_index(op.f('ix_transaction_logs_customer_id'), 'transaction_logs', ['customer_id'], unique=False)
    op.create_index(op.f('ix_transaction_logs_trace_id'), 'transaction_logs', ['trace_id'], unique=True)
    op.create_index(op.f('ix_transaction_logs_transaction_state'), 'transaction_logs', ['transaction_state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_logs_transaction_state'), table_name='transaction_logs')
    op.drop_index(op.f('ix_transaction_logs_trace_id'), table_name='transaction_logs')
    op.drop_index(op.f('ix_transaction_logs_customer_id'), table_name='transaction_logs')
    op.drop_index(op.f('ix_transaction_logs_biller_id'), table_name='transaction_logs')
    op.drop_table('transaction_logs')
    op.drop_index(op.f('ix_reconciliation_logs_trace_id'), table_name='reconciliation_logs')
    op.drop_table('reconciliation_logs')
    op.drop_index(op.f('ix_payment_idempotency_idempotency_key'), table_name='payment_idempotency')
    op.drop_table('payment_idempotency')
    op.drop_index(op.f('ix_nonce_registry_nonce'), table_name='nonce_registry')
    op.drop_table('nonce_registry')
    op.drop_index(op.f('ix_billers_biller_id'), table_name='billers')
    op.drop_table('billers')
    # ### end Alembic commands ###
