"""Add favorite billers table

Revision ID: 804f63dbc69c
Revises: 5dd71be783a8
Create Date: 2026-05-25 20:54:51.123407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '804f63dbc69c'
down_revision: Union[str, Sequence[str], None] = '5dd71be783a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_billers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('billeraccountid', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.String(length=50), nullable=False),
    sa.Column('biller_id', sa.String(length=50), nullable=False),
    sa.Column('short_name', sa.String(length=100), nullable=False),
    sa.Column('authenticators', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('registration_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deletion_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('autopay_status', sa.String(length=1), nullable=True),
    sa.Column('autopay_start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('autopay_end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('autopay_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=True),
    sa.Column('payment_account', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cprn', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_favorite_billers_biller_id'), 'favorite_billers', ['biller_id'], unique=False)
    op.create_index(op.f('ix_favorite_billers_billeraccountid'), 'favorite_billers', ['billeraccountid'], unique=True)
    op.create_index(op.f('ix_favorite_billers_customer_id'), 'favorite_billers', ['customer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_favorite_billers_customer_id'), table_name='favorite_billers')
    op.drop_index(op.f('ix_favorite_billers_billeraccountid'), table_name='favorite_billers')
    op.drop_index(op.f('ix_favorite_billers_biller_id'), table_name='favorite_billers')
    op.drop_table('favorite_billers')
    # ### end Alembic commands ###
