class Role:
  ADMIN = "ADMIN"
  OPERATOR = "OPERATOR"
  CLIENT = "CLIENT"
  AUDITOR = "AUDITOR"
  SECURITY_ANALYST = "SECURITY_ANALYST"
  CUSTOMER_SUPPORT = "CUSTOMER_SUPPORT"

# Map of roles to check inheritance or permissions
ROLE_HIERARCHY = {
  Role.ADMIN: [Role.ADMIN, Role.OPERATOR, Role.CLIENT, Role.AUDITOR, Role.SECURITY_ANALYST, Role.CUSTOMER_SUPPORT],
  Role.OPERATOR: [Role.OPERATOR, Role.CLIENT],
  Role.CLIENT: [Role.CLIENT],
  Role.AUDITOR: [Role.AUDITOR, Role.SECURITY_ANALYST],
  Role.SECURITY_ANALYST: [Role.SECURITY_ANALYST],
  Role.CUSTOMER_SUPPORT: [Role.CUSTOMER_SUPPORT]
}
