class Role:
  SUPER_ADMIN = "SUPER_ADMIN"
  ADMIN = "ADMIN"
  OPERATIONS = "OPERATIONS"
  AUDITOR = "AUDITOR"
  CLIENT = "CLIENT"
  
  # Backward compatibility aliases
  OPERATOR = "OPERATIONS"
  SECURITY_ANALYST = "AUDITOR"
  CUSTOMER_SUPPORT = "OPERATIONS"

# Map of roles to check inheritance or permissions
ROLE_HIERARCHY = {
  Role.SUPER_ADMIN: [Role.SUPER_ADMIN, Role.ADMIN, Role.OPERATIONS, Role.AUDITOR, Role.CLIENT],
  Role.ADMIN: [Role.ADMIN, Role.OPERATIONS, Role.AUDITOR, Role.CLIENT],
  Role.OPERATIONS: [Role.OPERATIONS, Role.CLIENT],
  Role.AUDITOR: [Role.AUDITOR],
  Role.CLIENT: [Role.CLIENT]
}
